name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker Compose
        run: docker compose version

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Check running containers
        run: docker ps

      - name: Stop containers
        run: docker compose down
